import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';

const routes: Routes = [
  { path: '', loadChildren: './tabs/tabs.module#TabsPageModule' },
  { path: 'tab1', loadChildren: './tab1/tab1.module#Tab1PageModule' },
  { path: 'tab4', loadChildren: './tab4/tab4.module#Tab4PageModule' },
  { path: 'tab5', loadChildren: './tab5/tab5.module#Tab5PageModule' },
  { path: 'location', loadChildren: './location/location.module#LocationPageModule' },
  { path: 'login', loadChildren: './login/login.module#LoginPageModule' },
  { path: 'register', loadChildren: './register/register.module#RegisterPageModule' },
  { path: 'set', loadChildren: './set/set.module#SetPageModule' },
  { path: 'invitation', loadChildren: './invitation/invitation.module#InvitationPageModule' },
  { path: 'select', loadChildren: './select/select.module#SelectPageModule' },
  { path: 'hand', loadChildren: './hand/hand.module#HandPageModule' },
  { path: 'appoint', loadChildren: './appoint/appoint.module#AppointPageModule' },
  { path: 'activitydetails', loadChildren: './activitydetails/activitydetails.module#ActivitydetailsPageModule' },
  { path: 'hddetails', loadChildren: './hddetails/hddetails.module#HddetailsPageModule' },
  { path: 'canyu', loadChildren: './canyu/canyu.module#CanyuPageModule' },
  { path: 'tab3', loadChildren: './tab3/tab3.module#Tab3PageModule' },
  { path: 'initiate', loadChildren: './initiate/initiate.module#InitiatePageModule' },
  { path: 'wishcontent', loadChildren: './wishcontent/wishcontent.module#WishcontentPageModule' },
  { path: 'news-at-me', loadChildren: './news-at-me/news-at-me.module#NewsAtMePageModule' },
  { path: 'sendsuccess', loadChildren: './sendsuccess/sendsuccess.module#SendsuccessPageModule' },
  { path: 'commentcont', loadChildren: './commentcont/commentcont.module#CommentcontPageModule' },
  { path: 'imgwish', loadChildren: './imgwish/imgwish.module#ImgwishPageModule' },
  { path: 'elsehomepage', loadChildren: './elsehomepage/elsehomepage.module#ElsehomepagePageModule' },
  { path: 'bootpage', loadChildren: './bootpage/bootpage.module#BootpagePageModule' },
  { path: 'searchdetails', loadChildren: './searchdetails/searchdetails.module#SearchdetailsPageModule' },
  { path: 'password', loadChildren: './password/password.module#PasswordPageModule' },
  { path: 'password0', loadChildren: './password0/password0.module#Password0PageModule' },
  { path: 'mine', loadChildren: './mine/mine.module#MinePageModule' },
  { path: 'checkupdate', loadChildren: './checkupdate/checkupdate.module#CheckupdatePageModule' },
  { path: 'aboutus', loadChildren: './aboutus/aboutus.module#AboutusPageModule' },
  { path: 'feedback', loadChildren: './feedback/feedback.module#FeedbackPageModule' },
  { path: 'help', loadChildren: './help/help.module#HelpPageModule' },
  { path: 'personalinfo', loadChildren: './personalinfo/personalinfo.module#PersonalinfoPageModule' },
  { path: 'personalcard', loadChildren: './personalcard/personalcard.module#PersonalcardPageModule' },
  { path: 'address', loadChildren: './address/address.module#AddressPageModule' },
  { path: 'realname', loadChildren: './realname/realname.module#RealnamePageModule' },
  { path: 'addaddress', loadChildren: './addaddress/addaddress.module#AddaddressPageModule' },
  { path: 'follow', loadChildren: './follow/follow.module#FollowPageModule' },
  { path: 'fans', loadChildren: './fans/fans.module#FansPageModule' },
  { path: 'addfriends', loadChildren: './addfriends/addfriends.module#AddfriendsPageModule' },
  { path: 'editadd', loadChildren: './editadd/editadd.module#EditaddPageModule' },
  { path: 'myactivities', loadChildren: './myactivities/myactivities.module#MyactivitiesPageModule' },
  { path: 'collection', loadChildren: './collection/collection.module#CollectionPageModule' },
  { path: 'money', loadChildren: './money/money.module#MoneyPageModule' },
  { path: 'authenticationdata', loadChildren: './authenticationdata/authenticationdata.module#AuthenticationdataPageModule' },
  { path: 'dianzan', loadChildren: './dianzan/dianzan.module#DianzanPageModule' },
  { path: 'my-prop', loadChildren: './my-prop/my-prop.module#MyPropPageModule' },
  { path: 'customerservice', loadChildren: './customerservice/customerservice.module#CustomerservicePageModule' },
  { path: 'sixininter', loadChildren: './sixininter/sixininter.module#SixininterPageModule' },
  { path: 'activityalbum', loadChildren: './activityalbum/activityalbum.module#ActivityalbumPageModule' },
  { path: 'avataralbum', loadChildren: './avataralbum/avataralbum.module#AvataralbumPageModule' },
  { path: 'checkpoint', loadChildren: './checkpoint/checkpoint.module#CheckpointPageModule' },
  { path: 'wishalbum', loadChildren: './wishalbum/wishalbum.module#WishalbumPageModule' },
  { path: 'albumx', loadChildren: './albumx/albumx.module#AlbumxPageModule' },
  { path: 'yaoqinghaou', loadChildren: './yaoqinghaou/yaoqinghaou.module#YaoqinghaouPageModule' },
  { path: 'intsuccess', loadChildren: './intsuccess/intsuccess.module#IntsuccessPageModule' },
  { path: 'random', loadChildren: './random/random.module#RandomPageModule' },
  { path: 'hdyijieshu', loadChildren: './hdyijieshu/hdyijieshu.module#HdyijieshuPageModule' },
  { path: 'yikaishi', loadChildren: './yikaishi/yikaishi.module#YikaishiPageModule' },
  { path: 'aitefirend', loadChildren: './aitefirend/aitefirend.module#AitefirendPageModule' },
  { path: 'wishfriend', loadChildren: './wishfriend/wishfriend.module#WishfriendPageModule' },
  { path: 'yaoyuecanyu', loadChildren: './yaoyuecanyu/yaoyuecanyu.module#YaoyuecanyuPageModule' },
  { path: 'myhome', loadChildren: './myhome/myhome.module#MyhomePageModule' },
  { path: 'winprize', loadChildren: './winprize/winprize.module#WinprizePageModule' },
  { path: 'winpage', loadChildren: './winpage/winpage.module#WinpagePageModule' },
  { path: 'my-conductactive', loadChildren: './my-conductactive/my-conductactive.module#MyConductactivePageModule' },
  { path: 'myclosedactivities', loadChildren: './myclosedactivities/myclosedactivities.module#MyclosedactivitiesPageModule' },
  { path: 'propmall', loadChildren: './propmall/propmall.module#PropmallPageModule' },
  { path: 'poster', loadChildren: './poster/poster.module#PosterPageModule' },
  { path: 'allprops', loadChildren: './allprops/allprops.module#AllpropsPageModule' },
  { path: 'successpayment', loadChildren: './successpayment/successpayment.module#SuccesspaymentPageModule' },
  { path: 'recharge', loadChildren: './recharge/recharge.module#RechargePageModule' },
  { path: 'exchange', loadChildren: './exchange/exchange.module#ExchangePageModule' },
  { path: 'viplevel', loadChildren: './viplevel/viplevel.module#ViplevelPageModule' },
  { path: 'xieyi', loadChildren: './xieyi/xieyi.module#XieyiPageModule' },
  { path: 'announcement', loadChildren: './announcement/announcement.module#AnnouncementPageModule' },
  { path: 'themebg', loadChildren: './themebg/themebg.module#ThemebgPageModule' },
  { path: 'theme', loadChildren: './theme/theme.module#ThemePageModule' },
  { path: 'headhanger', loadChildren: './headhanger/headhanger.module#HeadhangerPageModule' },
  { path: 'privilege', loadChildren: './privilege/privilege.module#PrivilegePageModule' },
  { path: 'leveldescription', loadChildren: './leveldescription/leveldescription.module#LeveldescriptionPageModule' },
  { path: 'welfare', loadChildren: './welfare/welfare.module#WelfarePageModule' },
  { path: 'startactivities', loadChildren: './startactivities/startactivities.module#StartactivitiesPageModule' },
  { path: 'game', loadChildren: './game/game.module#GamePageModule' },
  { path: 'uploadcredentials', loadChildren: './uploadcredentials/uploadcredentials.module#UploadcredentialsPageModule' },
  { path: 'uploadself', loadChildren: './uploadself/uploadself.module#UploadselfPageModule' },
  { path: 'game1', loadChildren: './game1/game1.module#Game1PageModule' },
  { path: 'countdown', loadChildren: './countdown/countdown.module#CountdownPageModule' },
  { path: 'otherfans', loadChildren: './otherfans/otherfans.module#OtherfansPageModule' },
  { path: 'otherfollow', loadChildren: './otherfollow/otherfollow.module#OtherfollowPageModule' },
  { path: 'othercollection', loadChildren: './othercollection/othercollection.module#OthercollectionPageModule' },
  { path: 'otherdianzan', loadChildren: './otherdianzan/otherdianzan.module#OtherdianzanPageModule' },
  { path: 'otherend', loadChildren: './otherend/otherend.module#OtherendPageModule' },
  { path: 'videowish', loadChildren: './videowish/videowish.module#VideowishPageModule' },
];
@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
  ],
  exports: [RouterModule]
})
export class AppRoutingModule {}
